# Copyright (c) 2026, nav_arena developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Derived robot USD assets: upstream files with nav_arena's fixes baked into a small override layer.

A robot asset sometimes needs static USD edits before it behaves in simulation (a wrong friction mode, an embedded
ground plane). Baking them into the asset beats patching the stage at runtime: no ``prestartup`` event, so physics
replication stays on, and every code path that spawns the robot gets the fix.

The derived asset is a tiny ``.usda`` that sublayers the untouched upstream file and carries only ``over`` opinions.
It is generated into the cache on first use and named with a hash of the source, so a changed upstream asset rebuilds
automatically. The upstream file is never modified, and no large binary is copied or committed.

This module is deliberately stdlib-only at import time: generation runs in a subprocess (``python assets.py ...``)
because importing ``pxr`` inside a script before ``AppLauncher`` boots crashes Kit. Looking up an already built asset
needs neither ``pxr`` nor a subprocess.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
import subprocess
import sys

_OVERRIDE_VERSION = "1"
"""Bump when the override text changes so cached derived assets are rebuilt."""


def _source_digest(source: Path) -> str:
    """Return a short content hash of ``source`` plus the override version."""
    digest = hashlib.sha256(_OVERRIDE_VERSION.encode())
    with source.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()[:8]


def derived_asset_path(name: str, source: Path, cache_dir: Path) -> Path:
    """Return where the derived asset for ``source`` lives (it may not exist yet)."""
    return cache_dir / "assets" / f"{name}_nav_arena_{_source_digest(source)}.usda"


def ensure_derived_asset(name: str, source: Path, cache_dir: Path) -> Path:
    """Return the derived asset for ``source``, generating it first if needed.

    Args:
        name: Asset name, currently only ``"dingo"``.
        source: Upstream USD file.
        cache_dir: Cache root; the asset goes under ``<cache_dir>/assets``.

    Raises:
        FileNotFoundError: If ``source`` does not exist.
        RuntimeError: If generation fails, e.g. the upstream asset no longer has the prims the override targets.
    """
    source = Path(source)
    if not source.is_file():
        raise FileNotFoundError(f"Source USD asset not found: {source}")
    target = derived_asset_path(name, source, Path(cache_dir))
    if target.is_file():
        return target
    target.parent.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        [sys.executable, str(Path(__file__).resolve()), name, str(source), str(target)],
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0 or not target.is_file():
        raise RuntimeError(f"Could not build derived '{name}' USD from {source}:\n{result.stderr or result.stdout}")
    return target


##
# Generation (runs in a subprocess; needs pxr)
##


def _dingo_override_text(source: Path, root: str, up_axis: str, meters_per_unit: float) -> str:
    """Return the USDA text overriding the Dingo's ground plane and caster friction."""
    return f"""#usda 1.0
(
    defaultPrim = "{root}"
    metersPerUnit = {meters_per_unit!r}
    upAxis = "{up_axis}"
    subLayers = [
        @{source}@
    ]
    doc = "Generated by nav_arena.embodiments.assets from the upstream Dingo asset; do not edit."
)

over "{root}"
{{
    # The asset ships its own collision floor, which would fight the scene's floor.
    over "GroundPlane" (
        active = false
    )
    {{
    }}

    # The passive caster is a frictionless sphere. With the default "average" combine mode the floor's friction would
    # be averaged in, so the caster drags and the drive wheels slip; "min" keeps the contact frictionless.
    over "PhysicsMaterials"
    {{
        over "caster_wheel" (
            prepend apiSchemas = ["PhysxMaterialAPI"]
        )
        {{
            token physxMaterial:frictionCombineMode = "min"
        }}
    }}
}}
"""


def build_dingo_override(source: Path, target: Path) -> None:
    """Write the derived Dingo layer for ``source`` to ``target`` (requires ``pxr``).

    Raises:
        RuntimeError: If the source lacks a default prim, ``GroundPlane`` or ``PhysicsMaterials/caster_wheel``.
    """
    from pxr import Sdf

    layer = Sdf.Layer.FindOrOpen(str(source))
    if layer is None:
        raise RuntimeError(f"Cannot open {source} as a USD layer")
    root = layer.defaultPrim
    if not root:
        raise RuntimeError(f"{source} has no defaultPrim")
    for suffix in ("GroundPlane", "PhysicsMaterials/caster_wheel"):
        if not layer.GetPrimAtPath(f"/{root}/{suffix}"):
            raise RuntimeError(
                f"{source} has no prim '/{root}/{suffix}'; the upstream Dingo asset layout changed and the "
                "nav_arena override needs updating."
            )
    up_axis = layer.pseudoRoot.GetInfo("upAxis") or "Z"
    meters_per_unit = float(layer.pseudoRoot.GetInfo("metersPerUnit") or 1.0)
    text = _dingo_override_text(Path(source).resolve(), root, str(up_axis), meters_per_unit)
    tmp = Path(str(target) + ".tmp")
    tmp.write_text(text)
    tmp.replace(target)


_BUILDERS = {"dingo": build_dingo_override}


def _main(argv: list[str]) -> int:
    if len(argv) != 4 or argv[1] not in _BUILDERS:
        print(f"usage: assets.py {{{'|'.join(_BUILDERS)}}} SOURCE TARGET", file=sys.stderr)
        return 2
    try:
        _BUILDERS[argv[1]](Path(argv[2]), Path(argv[3]))
    except Exception as error:  # noqa: BLE001 - reported to the parent process through stderr
        print(f"{type(error).__name__}: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(_main(sys.argv))
